# -*- coding: utf-8 -*-
"""build.py — 一键打包脚本（自动安装 PyInstaller 到隔离环境并构建）

用法：
    python build.py

产物：dist/nginx-manager-v{版本}.exe（单文件，双击即用）

版本号来源：backend/server.py 的 server_version，唯一单一来源。
打包前自动生成 version_info.py（Windows exe 属性），无需手动维护。
"""
from __future__ import annotations

import io
import os
import re
import subprocess
import sys

# Windows CI (cp1252) 遇到中文 print 会 UnicodeEncodeError，强制 stdout/stderr 用 UTF-8
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(ROOT, "nginx-manager.spec")
SERVER_PY = os.path.join(ROOT, "backend", "server.py")


def extract_version() -> str:
    """从 server.py 的 server_version 提取版本号（如 '0.3.1'）。"""
    with open(SERVER_PY, encoding="utf-8") as f:
        m = re.search(r'server_version\s*=\s*["\']nginx-manager/([\d.]+)["\']', f.read())
    if not m:
        sys.exit("[build] ERROR: cannot parse version from backend/server.py server_version")
    return m.group(1)


def generate_version_info(version: str) -> str:
    """动态生成 version_info.py（Windows exe 文件属性），返回文件路径。"""
    parts = version.split(".")  # "0.3.1" -> ["0","3","1"]
    # 补齐 4 段：major.minor.patch.0
    while len(parts) < 4:
        parts.append("0")
    filevers = ", ".join(parts[:4])
    path = os.path.join(ROOT, "version_info.py")
    content = f'''# Auto-generated by build.py — DO NOT EDIT
# Version source: backend/server.py server_version
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({filevers}),
    prodvers=({filevers}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([StringTable(u'080404b0', [
      StringStruct(u'CompanyName', u'nginx-manager'),
      StringStruct(u'FileDescription', u'nginx lightweight web manager'),
      StringStruct(u'FileVersion', u'{version}'),
      StringStruct(u'InternalName', u'nginx-manager'),
      StringStruct(u'OriginalFilename', u'nginx-manager-v{version}.exe'),
      StringStruct(u'ProductName', u'nginx-manager'),
      StringStruct(u'ProductVersion', u'{version}'),
      StringStruct(u'Language', u'Chinese (Simplified)')
    ])]),
    VarFileInfo([VarStruct(u'Translation', [2052, 1200])])
  ]
)
'''
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


def run(cmd, cwd=None):
    print(">>", " ".join(cmd))
    subprocess.check_call(cmd, cwd=cwd)


def main() -> int:
    # 1. 提取版本号
    version = extract_version()
    print(f"[build] version: {version}")

    # 2. 生成 version_info.py（Windows exe 属性）
    if sys.platform == "win32":
        vip = generate_version_info(version)
        print(f"[build] generated: {os.path.basename(vip)}")

    # 3. 检查 tkinter（启动选择框与「浏览」按钮依赖；缺则 exe 静默退化为预览模式）
    try:
        import tkinter  # noqa: F401
    except ImportError:
        print("[build] ERROR: tkinter not available in this Python.")
        print("         首次启动选择框与界面「浏览…」按钮都需要 tkinter（tcl/tk）。")
        print("         请改用自带 tcl/tk 的 Python 重新打包（而非 pip 安装的精简 Python）。")
        return 1

    # 4. 检查 PyInstaller
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("[build] installing PyInstaller...")
        run([sys.executable, "-m", "pip", "install", "--user", "pyinstaller"])
        try:
            import PyInstaller  # noqa: F401
        except ImportError:
            print("[build] ERROR: PyInstaller install failed")
            return 1

    # 5. 沙箱 shim：临时替换 os.remove 避免回收站策略干扰 PyInstaller
    _orig_remove, _orig_unlink = os.remove, os.unlink
    os.remove = lambda p, *a, **kw: _orig_remove(p) if os.path.isfile(p) else None
    os.unlink = os.remove

    build_dir = os.path.join(ROOT, "build")
    dist_dir = os.path.join(ROOT, "dist")
    for d in (build_dir, dist_dir):
        if os.path.isdir(d):
            backup = d + "_prev"
            try:
                if os.path.isdir(backup):
                    import shutil
                    shutil.rmtree(backup, ignore_errors=True)
                os.rename(d, backup)
            except OSError as e:
                print(f"[build] cleanup {d} failed (continuing): {e}")

    # 6. 执行 PyInstaller
    try:
        run([sys.executable, "-m", "PyInstaller", SPEC, "--noconfirm"])
    finally:
        os.remove, os.unlink = _orig_remove, _orig_unlink

    # 7. 查找产物
    expected = f"nginx-manager-v{version}"
    exe = None
    if os.path.isdir(dist_dir):
        for f in os.listdir(dist_dir):
            if f.startswith(expected):
                exe = os.path.join(dist_dir, f)
                break
    if exe and os.path.isfile(exe):
        size_mb = os.path.getsize(exe) / 1024 / 1024
        print(f"\n[build] OK: {exe} ({size_mb:.1f} MB)")
        return 0
    print(f"\n[build] FAILED: {expected} not found in {dist_dir}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
